### ISSUE TITLE
Spec Front End

### ISSUE THREAD

**Issue by DavidLu1997** [SEkiSoft/gogogo#33]
Spec front end

**Comment by Will-Lo** [comment]
Anyone is free to suggest modifications or if they have a better idea for doing this, but here's how I think it should be done in React.

The game itself is a container that has a game state (a 2d array), that specifies whether or not the piece at that particular cell is black, white or empty.

For every index in the array, render a cross section component (it'll have to have multiple different displays based on whether or not it's an edge cross section or corner cross section)

In every cross section, it renders a go piece component depending if the array cell has a black or white piece. If there is a piece, the cross section should no longer be clickable/do anything when clicked.

When the cross section is clicked by a player on their turn, the game state is updated appropriately, which re-renders the component with the appropriate game piece.

**Comment by Will-Lo** [comment]
Other things needed for front-end

1. Login screen and signup page
2. Scoreboard at the end of the game
3. Indicators for which player's turn

**Comment by tiffanynwyeung** [comment]
Cross-posted from our Slack channel:

- Default welcome page to GoGoGo. This includes signup/login screen, using email/password as well as Google account OAuth. 
    - Things to consider for future features: Facebook OAuth.
- User dashboard, including user profile (username, date joined, game statistics) and settings to change said profile information. 
    - Things to consider for future features: profile images, friends list.
- Game queuing: screens to display matchmaking, loading, "found a game", etc.
    - Things to consider for future features: social play
- Game display: scoreboard, turn-based indicators (when it is your turn/when opponent's turn, hitting an end turn button, etc.), game settings (e.g. concede match)

**Comment by DavidLu1997** [comment]
:+1: closing issue
