### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ian952** [SEkiSoft/gogogo#88]
We need a Logo for SEkiSoft

**Comment by ian952** [comment]
![sekisoftlogo](https://cloud.githubusercontent.com/assets/10297702/17724446/32468cd0-6410-11e6-87e0-a4e26c57be8f.png)

**Comment by Denton-L** [comment]
Logo with the most hearts by Monday is our official logo.

**Comment by Denton-L** [comment]
![image](https://cloud.githubusercontent.com/assets/9620836/17724480/63f7be8e-6410-11e6-82dc-7cd6d2980e67.png)

**Comment by tiffanynwyeung** [comment]
![sekisoftlogo](https://i.gyazo.com/6a6abbb094dae9afbfa0b1c1ed1601bd.png)

ignore color and background, but that font tho

**Comment by DavidLu1997** [comment]
Also `K` isn't capital in `SEkiSoft` @ian952

**Comment by Denton-L** [comment]
@tiffanynwyeung, it needs to be square...

**Comment by tiffanynwyeung** [comment]
@Denton-L i said LOOK AT THE FONT

**Comment by Denton-L** [comment]
Oh, that's what you meant. The font is sexy!

**Comment by emilyki** [comment]
![seki soft](https://cloud.githubusercontent.com/assets/15850091/17745820/5cd7da60-647b-11e6-9018-3c9e518c125b.png)

**Comment by emilyki** [comment]
black and white, circle cuz GO.

**Comment by Denton-L** [comment]
i actually really like this one. It's nice and simple. Can you press it together into one word, though?

**Comment by emilyki** [comment]
![seki soft](https://cloud.githubusercontent.com/assets/15850091/17746375/c5f107ae-647d-11e6-8475-11a17fc68b1a.png)
